name: 🤝 Join the Organization
description: Request to become a member of BotDev Community
title: "[JOIN] "
labels: ["join-request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 👋 Welcome to BotDev Community!
        
        Thanks for your interest in joining our organization! Please fill out the information below.
        
  - type: input
    id: github-username
    attributes:
      label: GitHub Username
      description: Your GitHub username (without the @)
      placeholder: username
    validations:
      required: true
      
  - type: input
    id: name
    attributes:
      label: Name or Alias
      description: What should we call you?
      placeholder: Your name
    validations:
      required: false
      
  - type: dropdown
    id: experience-level
    attributes:
      label: Bot Development Experience
      description: How experienced are you with bot development?
      options:
        - Beginner (just getting started)
        - Intermediate (built a few bots)
        - Advanced (experienced bot developer)
    validations:
      required: true
      
  - type: checkboxes
    id: platforms
    attributes:
      label: Platforms You've Worked With
      description: Which platforms have you built bots for? (Select all that apply)
      options:
        - label: WhatsApp
        - label: Telegram
        - label: Discord
        - label: Slack
        - label: Facebook Messenger
        - label: Twitter/X
        - label: Instagram
        - label: Other platforms
        
  - type: textarea
    id: tech-stack
    attributes:
      label: Tech Stack
      description: What technologies/languages do you use?
      placeholder: |
        e.g., Python, Node.js, FastAPI, Express, MongoDB, PostgreSQL, etc.
    validations:
      required: false
      
  - type: textarea
    id: projects
    attributes:
      label: Your Bot Projects
      description: Share links to your bot projects (if public)
      placeholder: |
        - https://github.com/yourusername/your-bot-repo
        - https://github.com/yourusername/another-project
    validations:
      required: false
      
  - type: checkboxes
    id: contribution-areas
    attributes:
      label: How You'd Like to Contribute
      description: What interests you most? (Select all that apply)
      options:
        - label: Add resources to awesome-bot-resources
        - label: Create starter templates for different platforms
        - label: Write tutorials and documentation
        - label: Review pull requests
        - label: Help answer community questions
        - label: Share bot development best practices
        - label: Contribute code to existing projects
        
  - type: textarea
    id: expertise
    attributes:
      label: Areas of Expertise
      description: Any specific skills or knowledge you bring?
      placeholder: |
        e.g., AI/LLM integration, webhook handling, deployment automation, 
        specific platform expertise, etc.
    validations:
      required: false
      
  - type: textarea
    id: motivation
    attributes:
      label: Why Join BotDev Community?
      description: What attracted you to this community?
      placeholder: Tell us what you hope to learn, build, or contribute
    validations:
      required: true
      
  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: By submitting this request, you agree to follow our community guidelines
      options:
        - label: I agree to follow the BotDev Community Code of Conduct
          required: true
          
  - type: markdown
    attributes:
      value: |
        ---
        
        ## 📋 What Happens Next?
        
        1. A maintainer will review your request
        2. We'll send you an invitation via GitHub
        3. Accept the invitation in your GitHub notifications
        4. Welcome to the community! 🎉
        
        **Note:** This may take 1-3 days. We review all requests to maintain quality.
