name: 📚 Submit a Resource
description: Suggest a new resource for awesome-bot-resources
title: "[RESOURCE] "
labels: ["resource-submission"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 📚 Submit a Resource
        
        Help us grow the best bot development resource list!
        
  - type: input
    id: resource-name
    attributes:
      label: Resource Name
      description: Name of the library, tool, or framework
      placeholder: e.g., python-telegram-bot
    validations:
      required: true
      
  - type: input
    id: url
    attributes:
      label: URL
      description: Link to the resource
      placeholder: https://github.com/python-telegram-bot/python-telegram-bot
    validations:
      required: true
      
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Where should this be added?
      options:
        - WhatsApp - Libraries
        - Telegram - Libraries
        - Discord - Libraries
        - Slack - Libraries
        - Messenger - Libraries
        - AI & NLP - LLM APIs
        - AI & NLP - NLP Libraries
        - Development Tools - Frameworks
        - Development Tools - Utilities
        - Deployment - Platforms
        - Testing - Frameworks
        - Learning Resources - Tutorials
        - Other (specify in description)
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of the resource (1-2 sentences)
      placeholder: A modern, pure Python async wrapper for the Telegram Bot API
    validations:
      required: true
      
  - type: dropdown
    id: maintenance
    attributes:
      label: Is it actively maintained?
      options:
        - "Yes - updated within the last 6 months"
        - "Yes - updated within the last year"
        - "No - but still useful"
    validations:
      required: true
      
  - type: input
    id: license
    attributes:
      label: License
      description: What license does it use?
      placeholder: MIT, Apache 2.0, GPL, etc.
    validations:
      required: false
      
  - type: textarea
    id: why
    attributes:
      label: Why is this valuable?
      description: Why should this be included?
      placeholder: |
        - Most popular Python library for Telegram bots
        - Comprehensive documentation
        - Active community support
    validations:
      required: true
      
  - type: checkboxes
    id: checklist
    attributes:
      label: Submission Checklist
      options:
        - label: I have tested this resource personally
        - label: The resource is publicly accessible
        - label: No duplicate entry exists in awesome-bot-resources
        - label: The link is working
